# dataset configuration
data_dir: ./dataset
dataset_name: /sep20-21
log_file: sep20-21.txt
embeddings: sep20-21/embeddings_average.json

# data preprocessing
grouping: sliding
sequential: true
semantic: false
quantitative: false
is_chronological: true

# model configuration
model_name: DeepLog
embedding_dim: 300 # default: 300, can range: from 32 to 1024
dropout: 0.1 # dropout rate: from 0.0 to 0.5
hidden_size: 64 # hidden size: from 32 to 1024 default: same as h
num_layers: 2 # number of layers: from 1 to 8
topk: 9 # default

# optimizer configuration
scheduler: linear
warmup_rate: 0.15 # range: from 0.01 to 0.2
lr: 0.001
adam_beta1: 0.9
adam_beta2: 0.999
optimizer: adamw
weight_decay: 0.0
optim_momentum: 0.9

# training configuration
accumulation_step: 1 # range: from 1 to 10
batch_size: 2048 # range: from 32 to 4096
max_epoch: 12 # range: from 1 to 100

# common configuration
step_size: 20
window_size: 20
train_size: 0.1
valid_ratio: 0.1
output_dir: ./output/
is_train: true
is_load: false
is_update: false
see_config: false
